spring:
  datasource:
    url: jdbc:mysql://54.162.171.163:3306/properties_db?useSSL=false&serverTimezone=UTC
    username: admin
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
